#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OLED Icon Maker — 从图片或手工像素生成 U8g2 drawXBMP 用的 C 头文件
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple


def _bootstrap_tcl_tk() -> bool:
    """
    在 import tkinter 之前设置 TCL_LIBRARY / TK_LIBRARY。
    常见故障：CSR BlueSuite 等软件把 TCL_LIBRARY 指到错误目录。
    """
    bases: list[str] = []
    for attr in ("base_prefix", "prefix"):
        p = getattr(sys, attr, None)
        if p and p not in bases:
            bases.append(p)

    exe = os.path.abspath(sys.executable)
    bases.append(os.path.dirname(exe))
    bases.append(os.path.dirname(os.path.dirname(exe)))  # .../Python313

    seen: set[str] = set()
    for base in bases:
        base = os.path.normpath(base)
        if base in seen:
            continue
        seen.add(base)
        tcl = os.path.join(base, "tcl", "tcl8.6")
        tk = os.path.join(base, "tcl", "tk8.6")
        init_tcl = os.path.join(tcl, "init.tcl")
        if os.path.isfile(init_tcl):
            os.environ["TCL_LIBRARY"] = tcl
            if os.path.isdir(tk):
                os.environ["TK_LIBRARY"] = tk
            return True
    return False


if not _bootstrap_tcl_tk():
    print(
        "错误: 未找到 Tcl/Tk（init.tcl）。\n"
        "请用 python.org 安装包重装 Python，并勾选 tcl/tk。\n"
        f"当前 Python: {sys.executable}",
        file=sys.stderr,
    )
    sys.exit(1)

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

try:
    from PIL import Image, ImageOps
except ImportError:
    Image = None  # type: ignore

APP_TITLE = "OLED 图标生成器 (U8g2 XBM)"
CELL = 14  # 网格每格显示像素
PREVIEW_SCALE = 4


def clamp(v: int, lo: int, hi: int) -> int:
    return max(lo, min(hi, v))


def empty_pixels(w: int, h: int) -> List[List[int]]:
    return [[0] * w for _ in range(h)]


def pixels_to_bytes(pixels: List[List[int]]) -> bytes:
    h = len(pixels)
    w = len(pixels[0]) if h else 0
    row_bytes = (w + 7) // 8
    out = bytearray(row_bytes * h)
    for y in range(h):
        for bx in range(row_bytes):
            value = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and pixels[y][x]:
                    value |= 1 << bit
            out[y * row_bytes + bx] = value
    return bytes(out)


def bytes_to_pixels(data: bytes, w: int, h: int) -> List[List[int]]:
    row_bytes = (w + 7) // 8
    pixels = empty_pixels(w, h)
    for y in range(h):
        for bx in range(row_bytes):
            value = data[y * row_bytes + bx]
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and (value & (1 << bit)):
                    pixels[y][x] = 1
    return pixels


def image_to_pixels(
    img: "Image.Image",
    w: int,
    h: int,
    threshold: int,
    invert: bool,
    dither: bool,
) -> List[List[int]]:
    gray = ImageOps.grayscale(img.resize((w, h), Image.Resampling.LANCZOS))
    if dither:
        gray = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
        bits = list(gray.getdata())
        pixels = empty_pixels(w, h)
        for y in range(h):
            for x in range(w):
                on = bits[y * w + x] == 0  # PIL 1-mode: 0=black
                pixels[y][x] = 1 if (on ^ invert) else 0
        return pixels

    pixels = empty_pixels(w, h)
    for y in range(h):
        for x in range(w):
            v = gray.getpixel((x, y))
            on = v < threshold
            pixels[y][x] = 1 if (on ^ invert) else 0
    return pixels


def parse_c_header(text: str) -> Optional[Tuple[str, int, int, List[List[int]]]]:
    name_m = re.search(r"unsigned\s+char\s+(\w+)\s*\[\]", text)
    w_m = re.search(r"#define\s+\w*ICON_W\s+(\d+)", text) or re.search(
        r"drawXBMP\s*\(\s*\d+\s*,\s*\d+\s*,\s*(\d+)", text
    )
    h_m = re.search(r"#define\s+\w+_H\s+(\d+)\s*$", text, re.MULTILINE)
    if not name_m:
        return None
    hex_bytes = re.findall(r"0x[0-9a-fA-F]{2}", text)
    if not hex_bytes:
        return None
    data = bytes(int(x, 16) for x in hex_bytes)
    w = int(w_m.group(1)) if w_m else 32
    h = int(h_m.group(1)) if h_m else len(data) // ((w + 7) // 8)
    if h <= 0:
        return None
    return name_m.group(1), w, h, bytes_to_pixels(data, w, h)


def generate_c_header(name: str, w: int, h: int, pixels: List[List[int]]) -> str:
    data = pixels_to_bytes(pixels)
    row_bytes = (w + 7) // 8
    prefix = name.upper()
    guard = f"{prefix}_INCLUDE_H"
    lines = [
        f"// Generated by OLED Icon Maker — {w}x{h} mono, U8g2 drawXBMP",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"#define {prefix}_W {w}",
        f"#define {prefix}_H {h}",
        f"// 128x64 OLED 右侧布局（可改屏幕尺寸时自行调整）",
        f"#define {prefix}_X (128 - {prefix}_W - 4)",
        f"#define {prefix}_Y ((64 - {prefix}_H) / 2)",
        "",
        f"static const unsigned char {name}[] U8X8_PROGMEM = {{",
    ]
    for y in range(h):
        row = data[y * row_bytes : (y + 1) * row_bytes]
        hexes = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"  {hexes},")
    lines += ["};", "", f"#endif  // {guard}", ""]
    return "\n".join(lines)


class OledIconMakerApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title(APP_TITLE)
        self.geometry("1100x720")
        self.minsize(900, 600)

        self.pixels: List[List[int]] = empty_pixels(32, 56)
        self.source_image: Optional[Image.Image] = None
        self.drag_value: Optional[int] = None

        self._build_ui()
        self._redraw_grid()
        self._redraw_preview()

    @property
    def width(self) -> int:
        return int(self.var_w.get())

    @property
    def height(self) -> int:
        return int(self.var_h.get())

    def _build_ui(self) -> None:
        top = ttk.Frame(self, padding=8)
        top.pack(fill=tk.X)

        ttk.Label(top, text="宽").pack(side=tk.LEFT)
        self.var_w = tk.IntVar(value=32)
        ttk.Spinbox(top, from_=8, to=128, width=5, textvariable=self.var_w).pack(
            side=tk.LEFT, padx=(2, 12)
        )
        ttk.Label(top, text="高").pack(side=tk.LEFT)
        self.var_h = tk.IntVar(value=56)
        ttk.Spinbox(top, from_=8, to=64, width=5, textvariable=self.var_h).pack(
            side=tk.LEFT, padx=(2, 12)
        )
        ttk.Button(top, text="应用尺寸", command=self._resize_canvas).pack(side=tk.LEFT, padx=4)
        ttk.Button(top, text="清空", command=self._clear_pixels).pack(side=tk.LEFT, padx=4)
        ttk.Button(top, text="反色", command=self._invert_pixels).pack(side=tk.LEFT, padx=4)

        ttk.Separator(top, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=8)
        ttk.Button(top, text="打开图片…", command=self._load_image).pack(side=tk.LEFT, padx=4)
        ttk.Button(top, text="导入 .h", command=self._import_header).pack(side=tk.LEFT, padx=4)

        mid = ttk.PanedWindow(self, orient=tk.HORIZONTAL)
        mid.pack(fill=tk.BOTH, expand=True, padx=8, pady=4)

        left = ttk.Frame(mid)
        mid.add(left, weight=3)

        img_opts = ttk.LabelFrame(left, text="图片转像素", padding=8)
        img_opts.pack(fill=tk.X)
        self.var_threshold = tk.IntVar(value=128)
        ttk.Label(img_opts, text="阈值 (越小越黑)").pack(anchor=tk.W)
        ttk.Scale(
            img_opts,
            from_=0,
            to=255,
            variable=self.var_threshold,
            orient=tk.HORIZONTAL,
            command=lambda _: self._preview_image_conversion(),
        ).pack(fill=tk.X)
        self.var_invert = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            img_opts, text="反色", variable=self.var_invert, command=self._preview_image_conversion
        ).pack(anchor=tk.W)
        self.var_dither = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            img_opts, text="Floyd-Steinberg 抖动", variable=self.var_dither, command=self._preview_image_conversion
        ).pack(anchor=tk.W)
        ttk.Button(img_opts, text="应用到像素网格 →", command=self._apply_image).pack(
            fill=tk.X, pady=(8, 0)
        )

        grid_frame = ttk.LabelFrame(left, text="像素编辑（点击切换；按住拖动绘制）", padding=4)
        grid_frame.pack(fill=tk.BOTH, expand=True, pady=8)
        self.canvas = tk.Canvas(grid_frame, bg="#222", highlightthickness=0)
        scroll_y = ttk.Scrollbar(grid_frame, orient=tk.VERTICAL, command=self.canvas.yview)
        scroll_x = ttk.Scrollbar(grid_frame, orient=tk.HORIZONTAL, command=self.canvas.xview)
        self.canvas.configure(yscrollcommand=scroll_y.set, xscrollcommand=scroll_x.set)
        scroll_y.pack(side=tk.RIGHT, fill=tk.Y)
        scroll_x.pack(side=tk.BOTTOM, fill=tk.X)
        self.canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self.canvas.bind("<Button-1>", self._on_grid_down)
        self.canvas.bind("<B1-Motion>", self._on_grid_drag)
        self.canvas.bind("<ButtonRelease-1>", self._on_grid_up)

        right = ttk.Frame(mid)
        mid.add(right, weight=1)
        prev_frame = ttk.LabelFrame(right, text="OLED 预览 (1:1)", padding=8)
        prev_frame.pack(fill=tk.BOTH, expand=True)
        self.preview = tk.Canvas(prev_frame, width=128, height=64, bg="#000", highlightthickness=1)
        self.preview.pack()
        ttk.Label(
            right,
            text="白=点亮像素\n右侧图标常用 32×56\n全屏图标可用 128×64",
            justify=tk.LEFT,
        ).pack(anchor=tk.W, pady=8)

        bottom = ttk.Frame(self, padding=8)
        bottom.pack(fill=tk.X)
        ttk.Label(bottom, text="C 变量名").pack(side=tk.LEFT)
        self.var_name = tk.StringVar(value="xbox360_icon")
        ttk.Entry(bottom, textvariable=self.var_name, width=24).pack(side=tk.LEFT, padx=6)
        ttk.Button(bottom, text="复制 C 代码", command=self._copy_c).pack(side=tk.LEFT, padx=4)
        ttk.Button(bottom, text="导出 .h 文件…", command=self._export_h).pack(side=tk.LEFT, padx=4)

        self.status = tk.StringVar(value="就绪")
        ttk.Label(bottom, textvariable=self.status).pack(side=tk.RIGHT)

    def _resize_canvas(self) -> None:
        w, h = self.width, self.height
        old = self.pixels
        oh, ow = len(old), (len(old[0]) if old else 0)
        self.pixels = empty_pixels(w, h)
        for y in range(min(h, oh)):
            for x in range(min(w, ow)):
                self.pixels[y][x] = old[y][x]
        self._redraw_grid()
        self._redraw_preview()
        self.status.set(f"画布 {w}×{h}")

    def _clear_pixels(self) -> None:
        self.pixels = empty_pixels(self.width, self.height)
        self._redraw_grid()
        self._redraw_preview()

    def _invert_pixels(self) -> None:
        for y in range(self.height):
            for x in range(self.width):
                self.pixels[y][x] ^= 1
        self._redraw_grid()
        self._redraw_preview()

    def _load_image(self) -> None:
        if Image is None:
            messagebox.showerror("缺少依赖", "请运行: pip install -r requirements.txt")
            return
        path = filedialog.askopenfilename(
            title="选择图片",
            filetypes=[
                ("图片", "*.png *.jpg *.jpeg *.bmp *.gif *.webp"),
                ("所有", "*.*"),
            ],
        )
        if not path:
            return
        try:
            self.source_image = Image.open(path).convert("RGB")
            self.status.set(f"已加载: {Path(path).name}")
            self._preview_image_conversion()
        except OSError as e:
            messagebox.showerror("打开失败", str(e))

    def _preview_image_conversion(self) -> None:
        if not self.source_image or Image is None:
            return
        temp = image_to_pixels(
            self.source_image,
            self.width,
            self.height,
            self.var_threshold.get(),
            self.var_invert.get(),
            self.var_dither.get(),
        )
        self._draw_preview_pixels(temp)

    def _apply_image(self) -> None:
        if not self.source_image:
            messagebox.showinfo("提示", "请先打开图片")
            return
        self.pixels = image_to_pixels(
            self.source_image,
            self.width,
            self.height,
            self.var_threshold.get(),
            self.var_invert.get(),
            self.var_dither.get(),
        )
        self._redraw_grid()
        self._redraw_preview()
        self.status.set("已从图片应用到网格")

    def _import_header(self) -> None:
        path = filedialog.askopenfilename(
            title="导入 C 头文件",
            filetypes=[("C 头文件", "*.h"), ("所有", "*.*")],
        )
        if not path:
            return
        text = Path(path).read_text(encoding="utf-8", errors="replace")
        parsed = parse_c_header(text)
        if not parsed:
            messagebox.showerror("解析失败", "未识别 U8X8_PROGMEM 数组或尺寸宏")
            return
        name, w, h, pixels = parsed
        self.var_name.set(name)
        self.var_w.set(w)
        self.var_h.set(h)
        self.pixels = pixels
        self._redraw_grid()
        self._redraw_preview()
        self.status.set(f"已导入 {path}")

    def _redraw_grid(self) -> None:
        self.canvas.delete("all")
        w, h = self.width, self.height
        for y in range(h):
            for x in range(w):
                x1, y1 = x * CELL, y * CELL
                x2, y2 = x1 + CELL - 1, y1 + CELL - 1
                fill = "#fff" if self.pixels[y][x] else "#333"
                self.canvas.create_rectangle(x1, y1, x2, y2, fill=fill, outline="#555", tags="cell")
        self.canvas.configure(scrollregion=(0, 0, w * CELL, h * CELL))

    def _redraw_preview(self) -> None:
        self._draw_preview_pixels(self.pixels)

    def _draw_preview_pixels(self, pixels: List[List[int]]) -> None:
        self.preview.delete("all")
        pw, ph = self.width, self.height
        ox = (128 - pw) // 2
        oy = (64 - ph) // 2
        for y in range(ph):
            for x in range(pw):
                if pixels[y][x]:
                    self.preview.create_rectangle(
                        ox + x, oy + y, ox + x + 1, oy + y + 1, fill="#fff", outline=""
                    )
        if pw < 128 or ph < 64:
            self.preview.create_rectangle(ox - 1, oy - 1, ox + pw, oy + ph, outline="#444")

    def _cell_at(self, event) -> Optional[Tuple[int, int]]:
        x = int(self.canvas.canvasx(event.x)) // CELL
        y = int(self.canvas.canvasy(event.y)) // CELL
        if 0 <= x < self.width and 0 <= y < self.height:
            return x, y
        return None

    def _set_cell(self, x: int, y: int, value: int) -> None:
        if self.pixels[y][x] == value:
            return
        self.pixels[y][x] = value
        self._redraw_preview()

    def _on_grid_down(self, event) -> None:
        cell = self._cell_at(event)
        if not cell:
            return
        x, y = cell
        self.drag_value = 1 - self.pixels[y][x]
        self._set_cell(x, y, self.drag_value)
        self._redraw_grid()

    def _on_grid_drag(self, event) -> None:
        if self.drag_value is None:
            return
        cell = self._cell_at(event)
        if cell:
            self._set_cell(cell[0], cell[1], self.drag_value)

    def _on_grid_up(self, _event) -> None:
        self.drag_value = None
        self._redraw_grid()

    def _c_text(self) -> str:
        name = re.sub(r"[^a-zA-Z0-9_]", "_", self.var_name.get().strip())
        if not name:
            name = "oled_icon"
        if name[0].isdigit():
            name = "icon_" + name
        return generate_c_header(name, self.width, self.height, self.pixels)

    def _copy_c(self) -> None:
        text = self._c_text()
        self.clipboard_clear()
        self.clipboard_append(text)
        self.status.set("C 代码已复制到剪贴板")

    def _export_h(self) -> None:
        name = self.var_name.get().strip() or "oled_icon"
        path = filedialog.asksaveasfilename(
            title="导出 C 头文件",
            defaultextension=".h",
            initialfile=f"{name}.h",
            filetypes=[("C 头文件", "*.h")],
        )
        if not path:
            return
        Path(path).write_text(self._c_text(), encoding="utf-8")
        self.status.set(f"已保存 {path}")
        messagebox.showinfo("完成", f"已导出:\n{path}\n\n复制到项目 include/ 后在固件中 #include 即可。")


def main() -> None:
    if Image is None:
        root = tk.Tk()
        root.withdraw()
        messagebox.showerror(
            "缺少 Pillow",
            "请先安装依赖:\n\npip install -r requirements.txt",
        )
        return
    app = OledIconMakerApp()
    app.mainloop()


if __name__ == "__main__":
    main()
